services:
  # SERVIÇO 1: BANCO DE DADOS
  postgres:
    image: postgres:15-alpine
    container_name: sentiment-db
    environment:
      POSTGRES_DB: sentiment_db
      POSTGRES_USER: oracle
      POSTGRES_PASSWORD: oracle_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # SERVIÇO 2: SUA API JAVA
  backend:
    build: .
    container_name: sentiment-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sentiment_db
      SPRING_DATASOURCE_USERNAME: oracle
      SPRING_DATASOURCE_PASSWORD: oracle_password
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

# DEFINIÇÃO DO VOLUME
volumes:
  postgres_data: